ALTER TABLE ATTRIBUTION
DROP FOREIGN KEY FK1_ATT;
ALTER TABLE ATTRIBUTION
DROP FOREIGN KEY FK2_ATT;



ALTER TABLE ATTRIBUTION
ADD CONSTRAINT FK1_ATT FOREIGN KEY (idEtab) REFERENCES Etablissement(id);
ALTER TABLE ATTRIBUTION
ADD CONSTRAINT FK2_ATT FOREIGN KEY (idGroupe) REFERENCES Groupe(id);