ALTER TABLE Attribution
DROP FOREIGN KEY FK1_ATT;
ALTER TABLE Attribution
DROP FOREIGN KEY FK2_ATT;



ALTER TABLE Attribution
ADD CONSTRAINT FK1_ATT FOREIGN KEY (idEtab) REFERENCES Etablissement(id);
ALTER TABLE Attribution
ADD CONSTRAINT FK2_ATT FOREIGN KEY (idGroupe) REFERENCES Groupe(id);